/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procesador;

import static java.lang.Thread.sleep;
import static procesador.Process.mCh;
import static procesador.Process.mIe;
import static procesador.RoundRobin.mrCh;
import static procesador.RoundRobin.mrIe;
import static procesador.SJN.msCh;
import static procesador.SJN.msIe;
import static procesador.SRT.mtCh;
import static procesador.SRT.mtIe;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static int ch; //una señal que nos indica que queremos iniciar tal proceso
    public static int iex;
    public static int mc;
    public static int im;
    public static int cd;
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Thread hilo = new Thread() {
            
            public void run() {
                
                for (;;) {
                    
                        try {
                            sleep(1000);
                            //poner un hilo para que se actualice el SO y muestre las ventanas requeridas
                            if(mCh==1 || mrCh==1 || msCh==1 || mtCh==1){
                                GoogleChrome g = new GoogleChrome();
                                miDesk.add(g);
                                g.show();
                                mCh=0;
                                mrCh=0;
                                msCh=0;
                                mtCh=0;
                            }
                            if(mIe==1 || mrIe==1 || msIe==1 || mtIe==1){
                                InternetExplorer i = new InternetExplorer();
                                miDesk.add(i);
                                i.show();
                                mIe=0;
                                mrIe=0;
                                msIe=0;
                                mtIe=0;
                            }
                            
                            
                        } catch (Exception e) {
                            System.out.println("error");
                        }

                    
                }
            }
        };
        hilo.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        miDesk = new javax.swing.JDesktopPane();
        chrome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        internet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mcafee = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        impresora = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        eyectar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        chrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/google-chrome-logo.png"))); // NOI18N
        chrome.setBorderPainted(false);
        chrome.setContentAreaFilled(false);
        chrome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chrome.setFocusable(false);
        chrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chromeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Google Chrome");

        internet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ielogo.png"))); // NOI18N
        internet.setBorderPainted(false);
        internet.setContentAreaFilled(false);
        internet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        internet.setFocusable(false);
        internet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Internet Explorer");

        mcafee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mclogo.png"))); // NOI18N
        mcafee.setBorderPainted(false);
        mcafee.setContentAreaFilled(false);
        mcafee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mcafee.setFocusable(false);
        mcafee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcafeeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("McAfee Security");

        impresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imlogo.png"))); // NOI18N
        impresora.setBorderPainted(false);
        impresora.setContentAreaFilled(false);
        impresora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        impresora.setFocusable(false);
        impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impresoraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Impresora");

        eyectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cdlogo.png"))); // NOI18N
        eyectar.setBorderPainted(false);
        eyectar.setContentAreaFilled(false);
        eyectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyectar.setFocusable(false);
        eyectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyectarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Expulsar CD");

        miDesk.setLayer(chrome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(internet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(mcafee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(impresora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(eyectar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout miDeskLayout = new javax.swing.GroupLayout(miDesk);
        miDesk.setLayout(miDeskLayout);
        miDeskLayout.setHorizontalGroup(
            miDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(miDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(miDeskLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(miDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(miDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chrome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(internet, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mcafee, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(impresora, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eyectar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        miDeskLayout.setVerticalGroup(
            miDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miDeskLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chrome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(internet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(mcafee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(eyectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(impresora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miDesk)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miDesk)
        );

        jMenu1.setText("Procesador");

        jMenuItem1.setText("FIFO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("RoundRobin");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("SJN");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("SRT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");

        jMenuItem5.setText("Comparar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Process ag = new Process();
        miDesk.add(ag);
        ag.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void chromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chromeActionPerformed
        ch=1;
    }//GEN-LAST:event_chromeActionPerformed

    private void internetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetActionPerformed
        iex=1;
    }//GEN-LAST:event_internetActionPerformed

    private void mcafeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcafeeActionPerformed
        mc=1;
    }//GEN-LAST:event_mcafeeActionPerformed

    private void impresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impresoraActionPerformed
        im=1;
    }//GEN-LAST:event_impresoraActionPerformed

    private void eyectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyectarActionPerformed
        cd=1;
    }//GEN-LAST:event_eyectarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RoundRobin rr = new RoundRobin();
        miDesk.add(rr);
        rr.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SJN sj = new SJN();
        miDesk.add(sj);
        sj.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SRT sr = new SRT();
        miDesk.add(sr);
        sr.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Comparar co = new Comparar();
        miDesk.add(co);
        co.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chrome;
    private javax.swing.JButton eyectar;
    private javax.swing.JButton impresora;
    private javax.swing.JButton internet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mcafee;
    private javax.swing.JDesktopPane miDesk;
    // End of variables declaration//GEN-END:variables
}
