/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procesador;

/**
 *
 * @author HP
 */
import static java.lang.Thread.sleep;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static procesador.Menu.ch;
import static procesador.Menu.iex;
import static procesador.Menu.mc;
import static procesador.Menu.im;
import static procesador.Menu.cd;
import static procesador.GoogleChrome.cerrarG; //queremos cerrar la ventana google
import static procesador.InternetExplorer.cerrarIe;
public class SRT extends javax.swing.JInternalFrame {

    /**
     * Creates new form SRT
     */
    public static int mtCh; //mostrar Chrome 
    public static int mtIe;
    public static double SRTE, SRTS, SRIS;
    boolean estado=true; 
    boolean ocupado=false; //si el procesador está ejecutando algo está ocupado
    ImageIcon imgCh = new ImageIcon(getClass().getResource("/imgs/chrMini.png"));
    ImageIcon imgChG = new ImageIcon(getClass().getResource("/imgs/google-chrome-logo.png"));
    ImageIcon imgIe = new ImageIcon(getClass().getResource("/imgs/ieMini.png"));
    ImageIcon imgIeG = new ImageIcon(getClass().getResource("/imgs/ielogo.png"));
    ImageIcon imgMc = new ImageIcon(getClass().getResource("/imgs/mcMini.png"));
    ImageIcon imgMcG = new ImageIcon(getClass().getResource("/imgs/mclogo.png"));
    ImageIcon imgIm = new ImageIcon(getClass().getResource("/imgs/imMini.png"));
    ImageIcon imgImG = new ImageIcon(getClass().getResource("/imgs/imlogo.png"));
    ImageIcon imgCd = new ImageIcon(getClass().getResource("/imgs/cdMini.png"));
    ImageIcon imgCdG = new ImageIcon(getClass().getResource("/imgs/cdlogo.png"));
    ImageIcon []logos = {imgCh,imgIe,imgMc,imgIm,imgCd};
    ImageIcon listos[]= new ImageIcon[3];
     int TiempoProcesos[]=new int[30];
    int TCh=500,TIe=500,TMc=500,TIm=500,TCd=500;
    ImageIcon susListos[]= new ImageIcon[3];
    ImageIcon bloqueados[]= new ImageIcon[2];
    ImageIcon susBloqueados[]= new ImageIcon[2];
    ImageIcon ejec[]= new ImageIcon[1];
    Proceso procesos[] = new Proceso[10];
    int ejCh, ejIe, ejMc, ejIm, ejCd; //para ejecutar tal proceso
    boolean chBloqueado=false, ieBloqueado=false, imBloqueado=false; //nos indica si hay un proceso bloqueado o sus bloqueado
    int t=0, tt=0; //contador que le mide el tiempo al proceso que se está ejecutando, y tt el tiempo total
    int tbim=0; //nos mide el tiempo que dura bloqueado la impresora
    int tiempoB3; //nos da el tiempo total que debe durar el bloqueo de la impresora
    int p; //aquí asignamos la posición del vector en la que está guardado el SRT
    int pGh, pIm, pIe, pMc, pCd; //las posiciones del vector donde están guardados chrome, ie e impresora
    int l; //se asignan aquí los valores de tiempo de ejecución en procesos
    int blocIm=0, blocG=0, blocIe=0; //para bloquear procesos
    boolean segundaVCh=false, segundaVIe=false, segundaVIm=false, segundaVCd=false, segundaVMc=false, terceraVCh=false, terceraVIe=false, terceraVIm=false;
    int comeCh, comeIe, comeMc, comeIm, comeCd; //el segundo en el que llegó tal proceso
    int trCh=200, trIe=200, trIm=200, trMc=200, trCd=200;
    public SRT() {
        initComponents();
        this.setLocation(200, 0);
        CrearQuantum();
        //poner un hilo para que se actualice el procesador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPEjec = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EspE = new javax.swing.JLabel();
        jPBloc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EspB3 = new javax.swing.JLabel();
        EspB2 = new javax.swing.JLabel();
        EspB1 = new javax.swing.JLabel();
        jPSusbloc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EspSB3 = new javax.swing.JLabel();
        EspSB2 = new javax.swing.JLabel();
        EspSB1 = new javax.swing.JLabel();
        jPListo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EspL1 = new javax.swing.JLabel();
        EspL2 = new javax.swing.JLabel();
        EspL3 = new javax.swing.JLabel();
        jPSuslisto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EspSL3 = new javax.swing.JLabel();
        EspSL2 = new javax.swing.JLabel();
        EspSL1 = new javax.swing.JLabel();
        action = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        Estadistica = new javax.swing.JButton();
        txtQuantum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTProceso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPEjec.setBackground(new java.awt.Color(255, 255, 255));
        jPEjec.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel3.setText("Ejecución");

        javax.swing.GroupLayout jPEjecLayout = new javax.swing.GroupLayout(jPEjec);
        jPEjec.setLayout(jPEjecLayout);
        jPEjecLayout.setHorizontalGroup(
            jPEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEjecLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(EspE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPEjecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPEjecLayout.setVerticalGroup(
            jPEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEjecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(EspE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPEjec);
        jPEjec.setBounds(450, 230, 130, 140);

        jPBloc.setBackground(new java.awt.Color(255, 255, 255));
        jPBloc.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Bloqueado");

        javax.swing.GroupLayout jPBlocLayout = new javax.swing.GroupLayout(jPBloc);
        jPBloc.setLayout(jPBlocLayout);
        jPBlocLayout.setHorizontalGroup(
            jPBlocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBlocLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPBlocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPBlocLayout.createSequentialGroup()
                        .addComponent(EspB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(EspB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(EspB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(34, 34, 34))
        );
        jPBlocLayout.setVerticalGroup(
            jPBlocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBlocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPBlocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EspB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPBloc);
        jPBloc.setBounds(60, 440, 200, 130);

        jPSusbloc.setBackground(new java.awt.Color(255, 255, 255));
        jPSusbloc.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel4.setText("Susp. Bloqueado");

        javax.swing.GroupLayout jPSusblocLayout = new javax.swing.GroupLayout(jPSusbloc);
        jPSusbloc.setLayout(jPSusblocLayout);
        jPSusblocLayout.setHorizontalGroup(
            jPSusblocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSusblocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSusblocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSusblocLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPSusblocLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(EspSB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EspSB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EspSB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPSusblocLayout.setVerticalGroup(
            jPSusblocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSusblocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPSusblocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EspSB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspSB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspSB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPSusbloc);
        jPSusbloc.setBounds(720, 440, 200, 130);

        jPListo.setBackground(new java.awt.Color(255, 255, 255));
        jPListo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Listo");

        javax.swing.GroupLayout jPListoLayout = new javax.swing.GroupLayout(jPListo);
        jPListo.setLayout(jPListoLayout);
        jPListoLayout.setHorizontalGroup(
            jPListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPListoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(EspL3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(EspL2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EspL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPListoLayout.setVerticalGroup(
            jPListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EspL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPListo);
        jPListo.setBounds(60, 30, 200, 130);

        jPSuslisto.setBackground(new java.awt.Color(255, 255, 255));
        jPSuslisto.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel2.setText("Susp. Listo");

        javax.swing.GroupLayout jPSuslistoLayout = new javax.swing.GroupLayout(jPSuslisto);
        jPSuslisto.setLayout(jPSuslistoLayout);
        jPSuslistoLayout.setHorizontalGroup(
            jPSuslistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSuslistoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSuslistoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(EspSL3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(EspSL2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EspSL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPSuslistoLayout.setVerticalGroup(
            jPSuslistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSuslistoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPSuslistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EspSL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspSL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspSL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPSuslisto);
        jPSuslisto.setBounds(730, 30, 200, 130);

        action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/play.png"))); // NOI18N
        action.setBorderPainted(false);
        action.setContentAreaFilled(false);
        action.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        action.setFocusable(false);
        action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionActionPerformed(evt);
            }
        });
        jPanel1.add(action);
        action.setBounds(450, 590, 80, 70);

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pause.png"))); // NOI18N
        pause.setBorderPainted(false);
        pause.setContentAreaFilled(false);
        pause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pause.setFocusable(false);
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        jPanel1.add(pause);
        pause.setBounds(450, 590, 80, 70);

        Estadistica.setBackground(new java.awt.Color(0, 0, 255));
        Estadistica.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Estadistica.setText("Mostrar Estadistica");
        Estadistica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticaActionPerformed(evt);
            }
        });
        jPanel1.add(Estadistica);
        Estadistica.setBounds(110, 610, 150, 23);

        txtQuantum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtQuantum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtQuantum.setEnabled(false);
        txtQuantum.setName("txtQuantum"); // NOI18N
        jPanel1.add(txtQuantum);
        txtQuantum.setBounds(430, 170, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tiempo de Proceso:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 150, 120, 15);

        txtTProceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTProceso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTProceso.setEnabled(false);
        txtTProceso.setName("txtQuantum"); // NOI18N
        jPanel1.add(txtTProceso);
        txtTProceso.setBounds(530, 170, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantum:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 150, 70, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionActionPerformed
        estado = true;
        action.setVisible(false);
        pause.setVisible(true);
        
        Thread hilo = new Thread() {
            
            public void run() {
                int c=0;
                for (;;) {
                    
                    if (estado == true) {
                        try {
                            sleep(500);
                            //poner un hilo para que se actualice el procesador
                            if(ch==1){
                               
                               ejCh=1;
                               p=nuevoProceso("Chrome");
                               pGh=p;
                               TCh=procesos[p].tiempo;
                               insertarListo(imgCh, TCh);
                               ch=0; //para que no se ponga en fila una y otra vez
                               comeCh=tt;
                               c++;
                            }
                            if(iex==1){
                               
                               ejIe=1;
                               p=nuevoProceso("Internet Explorer");

                               pIe=p;
                               
                               TIe=procesos[p].tiempo;
                               insertarListo(imgIe, TIe);
                               iex=0;
                               comeIe=tt;
                               c++;
                            }
                            if(mc==1){
                               
                               ejMc=1;
                               p=nuevoProceso("McAfee");

                               pMc=p;
                               TMc=procesos[p].tiempo;
                               insertarListo(imgMc, TMc);
                               mc=0;
                               comeMc=tt;
                               c++;
                            }
                            if(im==1){
                               
                               ejIm=1;
                               p=nuevoProceso("Impresora"); //Creamos clase proceso                               

                               pIm=p;
                               TIm=procesos[p].tiempo;
                               insertarListo(imgIm, TIm);
                               im=0;
                               comeIm=tt;
                               c++;
                            }
                            if(cd==1){
                               
                               ejCd=1;
                               
                               p=nuevoProceso("CD");

                               pCd=p;
                               TCd=procesos[p].tiempo;
                               insertarListo(imgCd, TCd);
                               cd=0; //para que no se ponga en fila una y otra vez
                               comeCd=tt;
                               c++;
                            }
                            mostrarListo();
                            mostrarSusListo();
                            mostrarBloqueado();
                            mostrarSusBloqueado();
                            sleep(500);
                            ejecutar();
                            //sorter();
                            //Imagenesenorden();
                            
                            
                        } catch (Exception e) {
                            System.out.println("error");
                        }

                    } else {
                        break;
                    }
                }
            }
        };
        hilo.start();
    }//GEN-LAST:event_actionActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        estado = false;
        action.setVisible(true);
        pause.setVisible(false);
    }//GEN-LAST:event_pauseActionPerformed

    private void EstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticaActionPerformed
        hacerEstadistica();
    }//GEN-LAST:event_EstadisticaActionPerformed

  public void insertarListo(ImageIcon logo, int time){

        if (listos[0]!=null) {
            if (listos[0]==logos[0]) {
                       p=pGh;
                   }
                   if (listos[0]==logos[1]) {
                       p=pIe;
                   }
                   if (listos[0]==logos[2]) {
                       p=pMc;
                   }
                   if (listos[0]==logos[3]) {
                       p=pIm;
                   }
                   if (listos[0]==logos[4]) {
                       p=pCd;
                   }
            if (time<procesos[p].tiempo) {
                susListos[2]=susListos[1];
                susListos[1]=susListos[0];
                susListos[0]=listos[2];
                listos[2]=listos[1];
                listos[1]=listos[0];
                listos[0]=logo;
                System.out.println("es menor que "+procesos[p].nombre);
                
            }else{
                if (listos[1]!=null) {
                    
                if (listos[1]==logos[0]) {
                       p=pGh;
                   }
                   if (listos[1]==logos[1]) {
                       p=pIe;
                   }
                   if (listos[1]==logos[2]) {
                       p=pMc;
                   }
                   if (listos[1]==logos[3]) {
                       p=pIm;
                   }
                   if (listos[1]==logos[4]) {
                       p=pCd;
                   }
                if (time<procesos[p].tiempo) {
                    susListos[2]=susListos[1];
                susListos[1]=susListos[0];
                susListos[0]=listos[2];
                listos[2]=listos[1];
                listos[1]=logo;
                System.out.println("es menor que "+procesos[p].nombre);
                } else {
                    if(listos[2]!=null){
                        if (listos[2]==logos[0]) {
                       p=pGh;
                   }
                   if (listos[2]==logos[1]) {
                       p=pIe;
                   }
                   if (listos[2]==logos[2]) {
                       p=pMc;
                   }
                   if (listos[2]==logos[3]) {
                       p=pIm;
                   }
                   if (listos[2]==logos[4]) {
                       p=pCd;
                   }
                    if (time<procesos[p].tiempo) {
                        susListos[2]=susListos[1];
                        susListos[1]=susListos[0];
                        susListos[0]=listos[2];
                        listos[2]=logo;
                        System.out.println("es menor que "+procesos[p].nombre);
                    } else {
                        insertarSusListo(logo, time);
                    }
                }else{
                        listos[2]=logo;
                    }
                }
                }else{
                    listos[1]=logo;
                }
            }
        } else {
            listos[0]=logo;
        }
        mostrarListo();
    }
    
    public void insertarSusListo(ImageIcon logo, int time){

        
        if (susListos[0]!=null) {
            if (susListos[0]==logos[0]) {
                       p=pGh;
                   }
                   if (susListos[0]==logos[1]) {
                       p=pIe;
                   }
                   if (susListos[0]==logos[2]) {
                       p=pMc;
                   }
                   if (susListos[0]==logos[3]) {
                       p=pIm;
                   }
                   if (susListos[0]==logos[4]) {
                       p=pCd;
                   }
            if (time<procesos[p].tiempo) {
                susListos[2]=susListos[1];
                susListos[1]=susListos[0];
                susListos[0]=logo;
                System.out.println("es menor que "+procesos[p].nombre);
                
            }else{
                if (susListos[1]!=null) {
                    
                if (susListos[1]==logos[0]) {
                       p=pGh;
                   }
                   if (susListos[1]==logos[1]) {
                       p=pIe;
                   }
                   if (susListos[1]==logos[2]) {
                       p=pMc;
                   }
                   if (susListos[1]==logos[3]) {
                       p=pIm;
                   }
                   if (susListos[1]==logos[4]) {
                       p=pCd;
                   }
                if (time<procesos[p].tiempo) {
                    susListos[2]=susListos[1];
                susListos[1]=logo;
                System.out.println("es menor que "+procesos[p].nombre);
                } else {
                    if(susListos[2]!=null){
                        if (susListos[2]==logos[0]) {
                       p=pGh;
                   }
                   if (susListos[2]==logos[1]) {
                       p=pIe;
                   }
                   if (susListos[2]==logos[2]) {
                       p=pMc;
                   }
                   if (susListos[2]==logos[3]) {
                       p=pIm;
                   }
                   if (susListos[2]==logos[4]) {
                       p=pCd;
                   }
                    if (time<procesos[p].tiempo) {
                        susListos[2]=logo;
                        System.out.println("es menor que "+procesos[p].nombre);
                    } else {
                        System.out.println("está lleno");
                    }
                }else{
                        susListos[2]=logo;
                    }
                }
                }else{
                    susListos[1]=logo;
                }
            }
        } else {
            susListos[0]=logo;
        }
        mostrarSusListo();
    }
    public void insertarBloqueado(ImageIcon logo){

        if (bloqueados[0]==null) {
            bloqueados[0]=logo;
            System.out.println("vacio");
        } else {
            if (bloqueados[1]==null) {
                bloqueados[1]=logo;
            } else {
                
                    
                        System.out.println("espacios en bloqueados ocupados");
                        insertarSusBloqueado(logo);
                    
                    }   
                }
    }
    public void insertarSusBloqueado(ImageIcon logo){

        if (susBloqueados[0]==null) {
            susBloqueados[0]=logo;
            System.out.println("vacio");
        } else {
            if (susBloqueados[1]==null) {
                susBloqueados[1]=logo;
            } else {
                
                    
                        System.out.println("espacios en sus bloqueados ocupados");
                        
                    
                    }   
                }
    }
    public void mostrarListo(){
        EspL1.setIcon(listos[0]);
        EspL2.setIcon(listos[1]);
        EspL3.setIcon(listos[2]);
    }
    public void mostrarSusListo(){
        EspSL1.setIcon(susListos[0]);
        EspSL2.setIcon(susListos[1]);
        EspSL3.setIcon(susListos[2]);
    }
    public void mostrarBloqueado(){
        EspB1.setIcon(bloqueados[0]);
        EspB2.setIcon(bloqueados[1]);
    }
    public void mostrarSusBloqueado(){
        EspSB1.setIcon(susBloqueados[0]);
        EspSB2.setIcon(susBloqueados[1]);
    }
    public void ejecutar() throws InterruptedException{
        if(ocupado==false){
            ejec[0]=listos[0]; //para que no esté vacio le asignamos la imagen actual
            if(!(ejec[0]==null)){
                
                ocupado=true;
                if(ejCh==1 && listos[0]==logos[0]){ //comparamos que chrome esté en espera y que el logo sea el que corresponda
                    EspE.setIcon(imgChG); //Imagen aumentada
                    if (segundaVCh==true) {
                        l=trCh;
                    }
                    if(terceraVCh==false && segundaVCh==false){
                        
                    System.out.println("mostrar chrome");
                    
                    ejCh=0; //para que no vuelva a generarse otro proceso igual
                   
                    l = procesos[p].tiempo;
                    
                    procesos[p].setLlegada(comeCh); //asignamos tiempo de llegada
                    pGh=p;
                    if (trCh==200) {
                            trCh=procesos[p].tiempo;
                        }
                    }
                    if(terceraVCh==true){
                        l=2;
                        ejCh=0;
                    }
                }
                if(ejIe==1 && listos[0]==logos[1]){
                    EspE.setIcon(imgIeG); //Imagen aumentada
                    if (segundaVIe==true) {
                        l=trIe;
                    }
                    if(terceraVIe==false && segundaVIe==false){
                    System.out.println("mostrar internet explorer");

                    ejIe=0;
                    
                    l = procesos[p].tiempo;
                    procesos[p].setLlegada(comeIe);
                    pIe=p;
                    if (trIe==200) {
                            trIe=procesos[p].tiempo;
                        }
                    }
                     if(terceraVIe==true){
                        l=2;
                        ejIe=0;
                        
                    }
                }
                if(ejMc==1 && listos[0]==logos[2]){
                    EspE.setIcon(imgMcG); //Imagen aumentada
                    if (segundaVMc==true) {
                        l=trMc;
                    }else{
                    System.out.println("ejecutando antivirus");
                    
                    ejMc=0;
                    
                    l = procesos[p].tiempo;
                    procesos[p].setLlegada(comeMc);
                    }
                    if (trMc==200) {
                            trMc=procesos[p].tiempo;
                        }
                }
                if(ejIm==1 && listos[0]==logos[3]){
                    EspE.setIcon(imgImG); //Imagen aumentada
                    if (segundaVIm==true) {
                        l=trIm;
                    }
                    if(terceraVIm==false && segundaVIm==false){
                    System.out.println("preparando impresión");
                    
                    ejIm=0;
                    //Creamos clase proceso
                    pIm=p;
                    l = procesos[p].tiempo; //tiempo de ejecución
                    procesos[p].setLlegada(comeIm);
                    if (trIm==200) {
                            trIm=procesos[p].tiempo;
                        }
                    }
                     if(terceraVIm==true){
                        l=2;
                        ejIm=0;
                        
                    }
                }
                if(ejCd==1 && listos[0]==logos[4]){ //comparamos que cd esté en espera y que el logo sea el que corresponda
                    EspE.setIcon(imgCdG); //Imagen aumentada
                    if (segundaVCd==true) {
                        l=trCd;
                    }else{
                    System.out.println("expulsando unidad CD");
                    
                    ejCd=0; //para que no vuelva a generarse otro proceso igual
                   
                    l = procesos[p].tiempo;
                    procesos[p].setLlegada(comeCd);
                    }
                    if (trCd==200) {
                            trCd=procesos[p].tiempo;
                        }
                }
                
        
                recorrerListos();
            }
        } else{
            t++;
            System.out.println("tiempo="+t);
            txtTProceso.setText("" + t);
            int quantum = Integer.parseInt(txtQuantum.getText());
            
            if(t == quantum){
                System.out.println("El tiempo y el quantum son iguales");
                //Icon imgEjec = EspE.getIcon();
                
//                mostrarListo();
//                mostrarSusListo();
//                mostrarBloqueado();
//                mostrarSusBloqueado();
                if (ejec[0]==logos[0]) {
                    
                    trCh=trCh-quantum;
                    segundaVCh=true;
                    ejCh=1;
                    insertarListo(ejec[0],trCh);
                }
                if (ejec[0]==logos[1]) {
                    trIe=trIe-quantum;
                    segundaVIe=true;
                    ejIe=1;
                    insertarListo(ejec[0],trIe);
                }
                if (ejec[0]==logos[2]) {
                    trMc=trMc-quantum;
                    segundaVMc=true;
                    ejMc=1;
                    insertarListo(ejec[0],trMc);
                }
                if (ejec[0]==logos[3]) {
                    trIm=trIm-quantum;
                    segundaVIm=true;
                    ejIm=1;
                    insertarListo(ejec[0],trIm);
                }
                if (ejec[0]==logos[4]) {
                    trCd=trCd-quantum;
                    segundaVCd=true;
                    ejCd=1;
                    insertarListo(ejec[0],trCd);
                }
                t = 0;
                txtTProceso.setText("");
                ejec[0] = null;
                EspE.setIcon(ejec[0]);
                ocupado=false;
//                recorrerListos();
                
                /*if(segundaVuelta == true){
                    estado = true;
                    l = trp;
                    System.out.println("parte 2");
                    //recorrerListos();
                }*/ 
            }
        }
        if(t==l){ //cuando se cumpla el tiempo de ejecución
                if(ejec[0]==logos[3] && terceraVIm==false){
                    blocIm=1; //se bloquea el proceso impresora
                    insertarBloqueado(ejec[0]);
                }
                if(ejec[0]==logos[0] && terceraVCh==false){
                    blocG=1; //se bloquea el proceso impresora
                    insertarBloqueado(ejec[0]);
                }
                if(ejec[0]==logos[1] && terceraVIe==false){
                    blocIe=1; //se bloquea el proceso impresora
                    insertarBloqueado(ejec[0]);
                }
                if(imgImG==EspE.getIcon() && terceraVIm==true){ //para que no se vuelvan a ejecutar y ya estén terminados en la segunda vuelta;
                    p=pIm;
                }
                if(imgChG==EspE.getIcon() && terceraVCh==true){
                    p=pGh;
                }
                if(imgIeG==EspE.getIcon() && terceraVIe==true){
                    p=pIe;
                }
                if(imgMcG==EspE.getIcon() && segundaVMc==true){
                    p=pMc;
                }
                if(imgCdG==EspE.getIcon() && segundaVCd==true){
                    p=pCd;
                }
                t=0;
                ocupado=false;
                ejec[0]=null;
                EspE.setIcon(ejec[0]);
                System.out.println("Se cumplió el tiempo de ejecución en "+tt);
                procesos[p].setFinal(tt);
            }
        if(blocG==1){ //para poner en bloqueo a Chrome
            t=0; //el tiempo de ejecución regresa a 0
            System.out.println("se debe mostrar");
            mtCh=1; //mostrar Google Chrome
            
            ocupado=false;

            ejec[0]=null;
            EspE.setIcon(ejec[0]);
            blocG=0;
            
            
        }
        if(blocIe==1){
            t=0; //el tiempo de ejecución regresa a 0
            mtIe=1; //mostrar Ie
            
            ocupado=false;

            ejec[0]=null;
            EspE.setIcon(ejec[0]);
            blocIe=0;
            
        }
        if(blocIm==1){
            t=0; //el tiempo de ejecución regresa a 0
            tiempoB3 = (int) (Math.random()*10+5); //tiempo que durará bloqueado
            ocupado=false;

            imBloqueado=true;
            ejec[0]=null;
            EspE.setIcon(ejec[0]);
            blocIm=0;
            
        }
        if(cerrarG==1){
            
                if(bloqueados[0]==logos[0] || bloqueados[1]==logos[0]){ //si el proceso está en Bloqueados
                    insertarListo(logos[0],2);
                }else{ //está en sus. Bloquados
                    insertarSusListo(logos[0],2);
                }
                eliminarBloqueados(logos[0]);
                terceraVCh=true;
                ejCh=1;
                cerrarG=0;
            
        }
        if(cerrarIe==1){
                cerrarIe=0;
                if(bloqueados[0]==logos[1] || bloqueados[1]==logos[1]){ //si el proceso está en Bloqueados
                    insertarListo(logos[1],2);
                }else{ //está en sus. Bloquados
                    insertarSusListo(logos[1],2);
                }

                eliminarBloqueados(logos[1]);
                terceraVIe=true;
                ejIe=1;
            
        }
        if(imBloqueado==true){
            tbim++; //contando tiempo bloqueado
            if(tbim>=tiempoB3){
                if(bloqueados[0]==logos[3] || bloqueados[1]==logos[3]){ //si el proceso está en Bloqueados
                    insertarListo(logos[3],2);
                }else{ //está en sus. Bloquados
                    insertarSusListo(logos[3],2);
                }
                imBloqueado=false;
                tbim=0;
                eliminarBloqueados(logos[3]);
                terceraVIm=true;
                ejIm=1;
            }
        }
        tt++;
    }
    public void recorrerListos(){
        for (int i = 0; i < listos.length-1; i++) { //se recorren los restantes excepto el ultimo lugar porque daría error
            listos[i]=listos[i+1];
        }
        listos[2]=susListos[0]; //poner aquí el que sigue en susListos
        susListos[0]=susListos[1];
        susListos[1]=susListos[2];
        susListos[2]=null;
    }
    public void eliminarBloqueados(ImageIcon logo){ //por ahora hasta aclarar duda

          if(bloqueados[0]==logo){ //se compara uno por uno con ifs para que así si hay mas de un proceso igual solo se elimine uno
              bloqueados[0]=null;
              System.out.println("Se eliminó en bloqueados 0");
          }else{
              if (bloqueados[1]==logo) {
                  bloqueados[1]=null;
              } else {
                  if (susBloqueados[0]==logo) {
                      susBloqueados[0]=null;
                  } else {
                      if (susBloqueados[1]==logo) {
                          susBloqueados[1]=null;
                      } 
                  }
              }
          }
          recorrerBloqueados();
    }
    public void recorrerBloqueados(){
        if(bloqueados[0]==null){ //solo si hay un espacio vacio se recorre
            bloqueados[0]=bloqueados[1];
            bloqueados[1]=susBloqueados[0];
            susBloqueados[0]=susBloqueados[1];
        }
        if(bloqueados[1]==null){
            bloqueados[1]=susBloqueados[0]; //poner aquí el que sigue en susListos
            susBloqueados[0]=susBloqueados[1];
        }
        if(susBloqueados[0]==null){
            susBloqueados[0]=susBloqueados[1];
        }
        susBloqueados[1]=null;
        
    }
    public int nuevoProceso(String nombre){
        int que=0;
        int p=0; //vamos a retornar la posición del vector en la que esta nuestro proceso, iniciamos en 0 por si el vector está lleno
        for(int t=0; t<procesos.length; t++){
               if(procesos[t]==null){ //comprobamos que esté vacio el espacio
                   
                   int n = JOptionPane.showConfirmDialog(null, "¿Desea agregar valores a los tiempos de ejecución?"
                           +"\n"+"Si elige no, entonces se asignarán valores aleatorios", "Asignar valores",JOptionPane.YES_NO_OPTION);
                   if(n==JOptionPane.YES_OPTION){
                       int tiempo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tiempo que durará en ejecución el proceso "+nombre));
                       procesos[t] = new Proceso(nombre, tiempo);
                   }else{
                       procesos[t] = new Proceso(nombre);
                   }
                   
                   procesos[t].setLogo(nombre);
                   
                   p=t;
                   
                   t = 100; //salimos del ciclo
               }
               else{
                   que = que+1; //por cada espacio de vector lleno aumenta 1
               }
             }
            if(que>=procesos.length){ //ya no hay espacios
                   JOptionPane.showMessageDialog(null, "Ya no hay espacio para crear mas procesos");
               }
            return p;
    }
    
    public void hacerEstadistica(){
        int i=0;
        double promT=0, promE=0, promI=0;
            while(procesos[i]!=null) {
                procesos[i].setTiempoServicio();
                procesos[i].setTiempoEspera();
                procesos[i].setIndiceServicio();
                System.out.println("----------------------------------------------------------------------------------");
                System.out.println("Nombre del proceso: "+procesos[i].getNombre()+"\n"
                +"Instante de llegada: "+procesos[i].llegada+"\n"
                +"Tiempo de ejecución: "+procesos[i].tiempo+"\n"
                +"Instante de fin: "+procesos[i].fin+"\n"
                +"Tiempo de servicio: "+procesos[i].T+"\n"
                +"Tiempo de espera: "+procesos[i].E+"\n"
                +"Indice de servicio: "+procesos[i].I+"\n");
                promT=promT+procesos[i].T;
                promE=promE+procesos[i].E;
                promI=promI+procesos[i].I;
                i++;
            
            }
            System.out.println("-------------------------------------");
            System.out.println("Promedio de Tiempo de servicio: "+(promT/i)+"\n"
            +"Promedio de Tiempo de espera: "+(promE/i)+"\n"
            +"Promedio de Indice de servicio: "+(promI/i)+"\n");
            SRIS=promT/i;
            SRTE=promE/i;
            SRTS=promI/i;
        
    }
    
    public void CrearQuantum(){
        int n = JOptionPane.showConfirmDialog(null, "¿Desea agregar un valor manual al quantum?"
                           +"\n"+"Si elige no, entonces se asignarán valores aleatorios", "Asignar valores",JOptionPane.YES_NO_OPTION);
                   if(n==JOptionPane.YES_OPTION){
                       int quantum = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tiempo que desea que tenga el quantum: "));
                       txtQuantum.setText(String.valueOf(quantum));
                   }else{
                       int quantum = (int) (Math.random()*5 + 5);
                       txtQuantum.setText(String.valueOf(quantum));
                   }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EspB1;
    private javax.swing.JLabel EspB2;
    private javax.swing.JLabel EspB3;
    private javax.swing.JLabel EspE;
    private javax.swing.JLabel EspL1;
    private javax.swing.JLabel EspL2;
    private javax.swing.JLabel EspL3;
    private javax.swing.JLabel EspSB1;
    private javax.swing.JLabel EspSB2;
    private javax.swing.JLabel EspSB3;
    private javax.swing.JLabel EspSL1;
    private javax.swing.JLabel EspSL2;
    private javax.swing.JLabel EspSL3;
    private javax.swing.JButton Estadistica;
    private javax.swing.JButton action;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPBloc;
    private javax.swing.JPanel jPEjec;
    private javax.swing.JPanel jPListo;
    private javax.swing.JPanel jPSusbloc;
    private javax.swing.JPanel jPSuslisto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pause;
    private javax.swing.JTextField txtQuantum;
    private javax.swing.JTextField txtTProceso;
    // End of variables declaration//GEN-END:variables

    private void insertarListo(ImageIcon ejec) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
